# Generated by Django 3.2 on 2021-05-03 10:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=users.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
