# Generated by Django 3.2 on 2021-05-03 10:51

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210503_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(default=bookings.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
