# Generated by Django 3.2 on 2021-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('photo_url', models.URLField()),
                ('advisor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
