# Generated by Django 3.2 on 2021-05-03 10:51

import advisors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_id',
            field=models.AutoField(default=advisors.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
