# Generated by Django 3.2 on 2021-05-03 10:53

import advisors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_alter_advisor_advisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_id',
            field=models.CharField(default=advisors.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
