# Generated by Django 3.2 on 2021-05-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0003_alter_advisor_advisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photo_url',
            field=models.URLField(max_length=1000),
        ),
    ]
